feat: propagate doc comments on flags and arguments
near-cli-rs/interactive-clap pull request #26
Opened 2024-12-12 22:36 UTC by dj8yfo

- **commented: add propagate doc attributes for clap's derive of `help` and `long_help`**
- **test: add test_doc_comments_propagate**
- **uncomment: propagating doc comments attributes**
- **chore: add dbg_cond! macro**
- **chore: add passthrough of `verbatim_doc_comment` attribute to clap**

2024-12-12 22:50 UTC, dj8yfo commented
`introspect` feature can be used to debug how derive proc macros work similar to the following:

```bash
# interactive-clap-derive folder
cargo test test_doc_comments_propagate --features introspect -- --nocapture 
# from repo root
cargo run --example struct_with_subargs --features interactive-clap-derive/introspect 
```

2025-01-06 20:09 UTC, dj8yfo commented
this is still draft, pending some small work on top of it

2025-01-24 23:04 UTC, dj8yfo commented
No changes will be added to this pr. 
This will be self-skimmed, a pr to near-cli-rs done with patch from this branch to demonstrate it still compiles, 
and a pr to cargo-near with the changes indended initially of flags documentation

2025-01-24 23:15 UTC, dj8yfo commented on interactive-clap-derive/src/tests/test_simple_struct.rs
> +            /// awarenes of its possible applications
TODO: add `#[interactive_clap(long)]` on both fields

2025-02-03 19:16 UTC, dj8yfo commented
this branch has been identified to cause a bug with 
printing the final command 

```bash
# test_refactored_interactive_clap
#  interactive-clap-derive v0.3.1 (proc-macro)
# https://github.com/dj8yfo/interactive-clap.git?branch=propagate_doc_comments_on_flags#6bc76721
near account view-account-summary network-config now
# main
# interactive-clap-derive v0.3.1 (proc-macro)
near account view-account-summary momentous-war.testnet network-config testnet now
```

the cause of the bug was narrowed down to be due to propagating
the doc attributes to intermetiate `CliVariant` struct, which messes up `ToCliArgs` 
trait derive (2-step derives when 1st derive generates a struct, annotated with 2nd-step trait derive macro, are somewhat tricky to figure out):

Adding 1 line with doc-comment to test https://github.com/near-cli-rs/interactive-clap/pull/26/commits/29c9aeaf7f219a7b7cc0fbaa8430d4586190d84d ,

results in the following snapshot change https://github.com/near-cli-rs/interactive-clap/actions/runs/13120732036/job/36605779439 .

2025-02-06 23:05 UTC, dj8yfo commented
@race-of-sloths include

2025-02-06 23:05 UTC, race-of-sloths commented
@dj8yfo Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Do you want to apply for monthly streak? Get 8+ score for a single PR this month and receive boost for race-of-sloths!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://race-of-sloths.com/images/bot-banner-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://race-of-sloths.com/images/bot-banner-light.svg">
    <img alt="Shows inviting banner with latest news." src="https://race-of-sloths.com/images/bot-banner-light.svg">
</picture>](https://race-of-sloths.com/latest-news)

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&pr=near-cli-rs/interactive-clap/26&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&pr=near-cli-rs/interactive-clap/26&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/dj8yfo?type=bot&pr=near-cli-rs/interactive-clap/26&theme=white">
</picture>](https://race-of-sloths.com/profile/dj8yfo)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/dj8yfo)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2025-02-07 13:50 UTC, akorchyn requested changes
I'll return back to it a bit later. Hard to keep up :)

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/debug.rs
> +        // no-op
I think you can use allow unused here.

and then you won't need to #[allow(clippy::unused_enumerate_index)] in other files

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/common_methods/choose_variant.rs
> +                            group.stream().to_string().replace(" ", "");
maybe split_whitespaces and then collect, or something like that. 
maybe some weirdo uses tabs or something like that and ignores fmt.

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +#[cfg(test)]
I think cfg test module should be at the end of the file

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +pub(super) mod common_methods;
should be at the top of the file

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +    pub(crate) mod to_cli_trait;
Same here, move them to the top.

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +    pub(crate) mod to_cli_trait;
Can you move the docs back to this file (or to the file itself)? I think it's crucial to keep it here, as it's mostly for internal devs, and it's not pleasant to search for a separate file. 

As a developer, I never build docs for my crate just to understand the logic.

This is pretty important point for me

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/docs/clap_enum_for_named_arg_docstring.md
> +derive of helper enum for structs with `#[interactive_clap(named_arg)]` on fields
It's internal doc, so I would better keep it with the code at the level with the code

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/structs/clap_for_named_arg_enum.rs
> +        .unwrap_or(quote!())
I know it was before, but should we put here that debug macro? to indicate that we ccouldn't transform?

2025-02-07 13:50 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/structs/to_cli_trait/clap_parser_trait_adapter/mod.rs
> +use proc_macro2::TokenStream;
maybe we can just clap_parser_trait_adapter.rs 

we don't have any submodules

2025-02-07 14:02 UTC, akorchyn commented
Can you create a patch release for near-cli-rs and check that it's starting speed is sufficient and not struggle as Vlad described on a call?

2025-02-07 14:24 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +    pub(crate) mod to_cli_trait;
yeap, ok
the thing is really convoluted to understand, that's why the doc. 
as a reference point to return later, when context will be forgotten. 
if it helps me navigate, maybe it'll help someone else, though the latter is unlikely

2025-02-07 14:34 UTC, dj8yfo commented
@akorchyn patch was created https://github.com/near/near-cli-rs/pull/444 , the starting lag is (visually) the same as in main

2025-02-07 15:58 UTC, akorchyn commented on src/lib.rs
> +//! Parser <https://crates.io/crates/clap>. Interactive-clap allows you to parse
```suggestion
//! Parser ([`CLAP`](https://crates.io/crates/clap>)). Interactive-clap allows you to parse
```

I think, it's better like that.

2025-02-07 15:58 UTC, akorchyn commented on examples/struct_with_subargs.rs
> +    #[interactive_clap(verbatim_doc_comment)]
`verbatim` is so weird word. Why `clap` hasn't used something more simple. Just a comment ignore

2025-02-07 15:58 UTC, akorchyn commented on interactive-clap-derive/src/tests/snapshots/interactive_clap_derive__tests__test_simple_struct__vec_multiple_opt.snap
> +impl Args {}
Seems like empty block somehow generated

2025-02-07 15:58 UTC, akorchyn commented on interactive-clap-derive/src/tests/snapshots/interactive_clap_derive__tests__test_simple_struct__vec_multiple_opt.snap
> +impl Args {}
I don't mean it's bad, just to check for you if it's intended

2025-02-10 10:53 UTC, dj8yfo commented on interactive-clap-derive/src/tests/snapshots/interactive_clap_derive__tests__test_simple_struct__vec_multiple_opt.snap
> +impl Args {}
It's intended when no input_arg functions were generated. Previously these were in a single block with clap parser adapter, which had slightly different purposes

2025-02-10 10:54 UTC, dj8yfo commented on examples/struct_with_subargs.rs
> +    #[interactive_clap(verbatim_doc_comment)]
verbatim (not comparable)

Word for word; in exactly the same words as were used originally.
I have copied his speech verbatim, so this is exactly what he said, word for word.

It was used in a sense, that this attr preserves original whitespace

2025-02-10 12:15 UTC, akorchyn commented on examples/struct_with_subargs.rs
> +    #[interactive_clap(verbatim_doc_comment)]
Yeah I goggled it, weird word anyway

2025-02-10 17:23 UTC, dj8yfo commented on interactive-clap-derive/src/debug.rs
> +        // no-op
addressed by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/87848e439f6f54b62a1a042fe19a498d47744e35

2025-02-10 17:30 UTC, dj8yfo commented on interactive-clap-derive/src/debug.rs
> +        // no-op
and then this popped up too https://github.com/near-cli-rs/interactive-clap/pull/26/commits/bc0a3639499dc353cfa6c6a9416a628b8c890a74

2025-02-10 17:33 UTC, dj8yfo commented on interactive-clap-derive/src/debug.rs
> +        // no-op
eventually getting rid of `#[allow(clippy::unused_enumerate_index)]` could be done, but it required
returning an unused expression. Probably compiler will optimize it out anyway, so it's not much of a big deal

2025-02-10 17:43 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/structs/clap_for_named_arg_enum.rs
> +        .unwrap_or(quote!())
i don't quite understand the suggestion. 
if the `dbg_cond!` macro is implied, i only added it to the paths i had trouble with figuring out for adding tests/looking at a bug or just generally figuring them out.
there many more possible paths to cover with debug statements, i think there're at least 100x more of them.

2025-02-10 17:52 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/structs/clap_for_named_arg_enum.rs
> +        .unwrap_or(quote!())
i beleive this module was a product of extracting this chunk of code 
https://github.com/near-cli-rs/interactive-clap/pull/26/files#diff-f36bdc4e97c2bde45b6fdb5764c7a15faf2ab71c0fcd30d123dac570724594c0L147-L192 . 
(Github UI doesn't seem to be capable of autoexpanding this link to the exact chunk, you would have to scroll to `interactive-clap-derive/src/derives/interactive_clap/mod.rs` file and click `Load file` button to be able to see the exact chunk, without clicking any other links or buttons, or Github will overwrite the info about chunk in URL).

2025-02-10 17:54 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/structs/clap_for_named_arg_enum.rs
> +        .unwrap_or(quote!())
added link to the chunk in the pr's base branch https://github.com/near-cli-rs/interactive-clap/blob/master/interactive-clap-derive/src/derives/interactive_clap/mod.rs#L147-L192 , this appears to work straightforwardly.

2025-02-10 20:35 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +pub(super) mod common_methods;
resolved by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/aad7bda7a14aeae49fe5a0407e879f8e08e0719b

2025-02-10 20:36 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +    pub(crate) mod to_cli_trait;
the first comment in this group is resolved by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/aad7bda7a14aeae49fe5a0407e879f8e08e0719b

2025-02-10 20:36 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +#[cfg(test)]
resolved by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/aad7bda7a14aeae49fe5a0407e879f8e08e0719b

2025-02-10 20:51 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/common_methods/choose_variant.rs
> +                            group.stream().to_string().replace(" ", "");
it actually wasn't dependent on presence of whitespace in original source code input, but rather defined
by https://docs.rs/proc-macro2/latest/proc_macro2/struct.TokenStream.html#impl-Display-for-TokenStream

the only weirdo who could change this to using tabs would be https://crates.io/users/dtolnay, which is unlikely

2025-02-10 20:55 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/common_methods/choose_variant.rs
> +                            group.stream().to_string().replace(" ", "");
resolved by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/9bedd978f3bc377ae518335723ae4e8f74e0c978

2025-02-10 21:09 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/structs/to_cli_trait/clap_parser_trait_adapter/mod.rs
> +use proc_macro2::TokenStream;
resolved by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/804e12028894841a232687d37b00358b3df0de79

2025-02-10 21:10 UTC, dj8yfo commented on interactive-clap-derive/docs/clap_enum_for_named_arg_docstring.md
> +derive of helper enum for structs with `#[interactive_clap(named_arg)]` on fields
assumed this to be the duplicate of https://github.com/near-cli-rs/interactive-clap/pull/26#discussion_r1946533737

2025-02-10 21:21 UTC, dj8yfo commented on interactive-clap-derive/src/tests/snapshots/interactive_clap_derive__tests__test_simple_struct__vec_multiple_opt.snap
> +impl Args {}
i'll try to remember to try include comments into generated output itself in another pr, 
and see if it breaks anything. Shouldn't break anything at all, but should probably be checked first
```rust
    quote! {
        // derived implementation block for `#name` struct, which contains functions `input_#field_ident` per each field,
        // which prompt for value of each field via [inquire::CustomType](https://docs.rs/inquire/0.6.2/inquire/struct.CustomType.html)
        impl #name {
            #(#vec_fn_input_arg)*
        }
    }
```

2025-02-10 21:37 UTC, dj8yfo commented on interactive-clap-derive/src/derives/interactive_clap/mod.rs
> +    pub(crate) mod to_cli_trait;
the second comment in this group is resolved by https://github.com/near-cli-rs/interactive-clap/pull/26/commits/c9cce0657048596087c4c86b4f6441167903c478

the paths of references have changed depending whether it was a /// comment outside of module , or /*! inside of one https://github.com/near-cli-rs/interactive-clap/actions/runs/13250874042/job/36988191297?pr=26

2025-02-11 10:22 UTC, akorchyn approved these changes
Small nit. Feel free to ignore. 

I think, we should avoid to make refactoring and feature addition in the same PR, but I also tend to do the same. 

@race-of-sloths score 13

2025-02-11 10:22 UTC, akorchyn commented on interactive-clap-derive/src/derives/interactive_clap/common_methods/choose_variant.rs
> +        for (_index, attr) in ast.attrs.clone().into_iter().enumerate() {
can be used already as index, but doesn't matter

2025-02-11 10:50 UTC, merged